apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-app
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/amol8090/k8s-project.git 
    targetRevision: main
    path: .
  destination: 
    server: https://kubernetes.default.svc 
    namespace: capstone-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace = true
