quota:
  requestsCpu: "2"
  requestsMemory: 2Gi
  limitCpu: "4"
  limitMemory: 4Gi
  maxPods: "20"

limitRange:
  defaultCpu: "200m"
  defaultMemory: "256Mi"
  defaultRequestCpu: "100m"
  defaultRequestMemory: "128Mi"

db:
  password: amolgore8090
  
postgres:
  replicas: 1
  tag: "16"
  storage: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"