apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{.Values.backend.replicas}}
  selector:
    matchLabels: 
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "httpd:{{.Values.backend.tag}}"
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "postgres-headless"
            
          resources:
            requests:
              cpu: {{.Values.backend.resources.requests.cpu}}
              memory: {{.Values.backend.resources.requests.memory}}
            limits:
              cpu: {{.Values.backend.resources.limits.cpu}}
              memory: {{.Values.backend.resources.limits.memory}}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

